### ISSUE TITLE
Running into issues getting it to run

### ISSUE THREAD

**Issue by reywright** [figus-cli/figus#10]
![ScreenShot 2022-11-22 at 16 31 34@2x](https://user-images.githubusercontent.com/708820/203435149-0b3a66b7-22c7-4313-9d4a-4df28514520c.png)

I seemingly have everything configured correctly, but it renders a generic error when running the npx command. I've tried for about 2 hours trying different things, but nothing works.

**Comment by omridevk** [comment]
seems like one of the figma parameters are wrong, I assume it is the file key or the token.
How did you generate the token?

**Comment by reywright** [comment]
Thanks! You're right, it was the file key 😌 So I corrected that. Now this is what I get:

![ScreenShot 2022-11-23 at 09 15 12@2x](https://user-images.githubusercontent.com/708820/203582155-71017020-a13f-4686-b088-8817dd407751.png)

I assume this means that the configuration is setup correctly, but maybe the Figma file is not?

So I guess I have a bunch of questions here:

1. The Figma file I'm using actually works for a lot of alternative Figma scripts. I'm assuming you approach it differently and require a certain setup / organization in Figma for this to generate properly.
2. How do I set it up? Do you have an example Figma file that I could look at?
3. I'm curious (after knowing the setup you're package is looking for) if you have opinions on which setup is better (the one for your package, vs this one that I'm using which works for other packages) and why that is.

**Comment by omridevk** [comment]
I used this page for testing:
https://www.figma.com/file/4IsUdFzDfZJteGV6rGi75h/Free-Icon-Pack-1600%2B-icons-(Community)?node-id=2%3A27&t=9FrBfDNpx2fPW8Bp-0

**Comment by omridevk** [comment]
```
import { defineConfig } from "@figus/cli";

export default defineConfig({
    output: "test",
    framework: "vue",
    path: "./src/assets",
    fontName: "omri",
    figma: {
        fileKey: "M5BTcQM09Vv1DRWFGscUBd",
    },
});

```

**Comment by reywright** [comment]
Thank you!! That finally worked for me. And the workflow seems to basically download the Figma file (`npx @figus/cli download`), which basically downloads all the `.svg` files puts them in `path`... and then to run `npx @figus/cli` which generates the components 🙌 I'll need to figure out how the templating of the React component works, but this looks really good so far! Will report back.

**Comment by reywright** [comment]
The file explorer seems to be having a bit of trouble rendering the icons here.

<img width="891" alt="ScreenShot 2022-11-24 at 07 55 26@2x" src="https://user-images.githubusercontent.com/708820/203801386-4961d313-2a3c-4ba6-90d7-da7b57e370ce.png">
