### ISSUE TITLE
White squares showing for @figus/cli explorer

### ISSUE THREAD

**Issue by silouanwright** [figus-cli/figus#11]
This is what I see when booting up the explorer.

![ScreenShot 2022-11-24 at 08 11 39@2x](https://user-images.githubusercontent.com/708820/203804938-c279a33e-96b9-4ea5-b444-69ca27af7104.png)

There's a bunch of white squares, which seem to be caused from this bit of CSS here. Disabling it makes everything appear fine.

<img width="922" alt="ScreenShot 2022-11-24 at 08 12 38@2x" src="https://user-images.githubusercontent.com/708820/203805091-51b831dd-a48c-4109-a02d-4399553a5596.png">

**Comment by omridevk** [comment]
I guess I didn't check it in light mode.
will fix soon, thanks a lot for reporting.
