### ISSUE TITLE
[Feature Request] Control over naming of icons

### ISSUE THREAD

**Issue by silouanwright** [figus-cli/figus#12]
Current, the icon component file names (and component names) are generated based on some internal formatting rules. So a `arrow_up_outlined` component would turn into `ArrowUpOutlined`. It would be great if this formatting function was exposed (or an equivalent solution), so that we could tune this formatting. 

For instance, I'd like to be able to suffix every name with `Icon`, so `arrow_up_outlined` turns into `ArrowUpOutlinedIcon`. I usually like the suffix as it quickly identifies it as an Icon component, and potentially reduces name clashes in the code base.

**Comment by omridevk** [comment]
there's this config option that can allow you to change the component name:
https://github.com/figus-cli/figus/blob/main/packages/types/src/options.ts#L26

**Comment by reywright** [comment]
Thanks! Seem to be running into issues though. I tried blowing all the files away too, and still got nothing. I'll see if I can debug and discover any issues.

![ScreenShot 2022-11-25 at 18 02 10@2x](https://user-images.githubusercontent.com/708820/204064346-210a576b-7a1a-4241-b454-0b3da78ade62.png)

**Comment by reywright** [comment]
Thanks!

<img width="545" alt="ScreenShot 2022-11-25 at 18 14 41@2x" src="https://user-images.githubusercontent.com/708820/204065124-2cbdd4f0-697a-48ff-a8c6-5bfb85d983e0.png">

Like this right? I'm struggling getting that to work for me.

**Comment by reywright** [comment]
I did figure out this, which allows someone to change filename ☺️ 

<img width="750" alt="ScreenShot 2022-11-25 at 18 43 50@2x" src="https://user-images.githubusercontent.com/708820/204066016-913b7e5b-064e-45ed-9cec-e0280065be34.png">

**Comment by omridevk** [comment]
yes, the 

> Thanks! Like this right?
> 
> ![ScreenShot 2022-11-25 at 18 14 41@2x](https://user-images.githubusercontent.com/708820/204065279-1b4453c3-866c-4b40-8448-c7d2e9717367.png)
> 
> I'm struggling getting that to work for me.
> 
> Edit: Actually... question! Does this work alongside the mustache templates? Will `{{{componentName}}}` spit out the value returned in `getComponentName`? I really like the mustache templates, but I don't know how I'd customize the casing of component names with it. Then I'm also curious how this interacts with the `getFileName` function 🤔

Yes, getComponentName should be available in the template, and it should be the value returned from ```getComponentName```

**Comment by omridevk** [comment]
see example of getComponentName implementation:
https://github.com/figus-cli/figus/blob/main/packages/react/src/getComponentName.ts
